apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sa.yaml
  - psp.yaml
  - rbac.yaml
  - service.yaml
  - statefulset.yaml
  - daemonset.yaml
  - cm.yaml

configMapGenerator:
  - name: loki-config
    files:
      - files/loki.yaml
