apiVersion: v1
kind: Secret
metadata:
  name: loki
  labels:
    app: loki
data:
  loki.yaml: |
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 0
    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    schema_config:
      configs:
      - from: 2020-01-01
        store: aws
        object_store: aws
        schema: v9
        index:
          prefix: {{.DYNAMODB_TABLE_NAME}}
          period: 0
    server:
      http_listen_port: 3100
    storage_config:
      s3: s3://{{.AWS_ACCESS_KEY_ID}}:{{.AWS_SECRET_ACCESS_KEY}}@ap-southeast-2/{{.S3_BUCKET_NAME}}
      dynamodbconfig:
        dynamodb: dynamodb://{{.AWS_ACCESS_KEY_ID}}:{{.AWS_SECRET_ACCESS_KEY}}@ap-southeast-2
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0
