apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sa.yaml
  - crd.yaml
  - role.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - hpa.yaml
  - monitor.yaml

configMapGenerator:
  - name: traefik-config
    files:
      - files/traefik.yaml
      - files/dynamic.yaml
