---
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: default-traefik
      labels:
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-9.8.1
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: default
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    spec:
      type: LoadBalancer
      selector:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: default
      ports:
      - name: web
        protocol: TCP
        port: 80
        targetPort: web
        nodePort: 30665
      - name: websecure
        protocol: TCP
        port: 443
        targetPort: websecure
        nodePort: 30675
