---
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: default-traefik
      labels:
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-9.8.1
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: default
      annotations:
    spec:
      type: NodePort
      selector:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: default
      ports:
      - port: 8080
        name: web
        targetPort: "web"
        protocol: "TCP"
        nodePort: 30101
      - port: 9080
        name: web-int
        targetPort: "web-int"
        protocol: "TCP"
        nodePort: 30103
      - port: 8443
        name: websecure
        targetPort: "websecure"
        protocol: "TCP"
        nodePort: 30100
      - port: 9443
        name: websecure-int
        targetPort: "websecure-int"
        protocol: "TCP"
        nodePort: 30102
