---
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: default-traefik
      labels:
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-9.19.0
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: default
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    spec:
      type: LoadBalancer
      selector:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: default
      ports:
      - port: 80
        name: web
        targetPort: "web"
        protocol: "TCP"
        nodePort: 30101
      - port: 443
        name: websecure
        targetPort: "websecure"
        protocol: "TCP"
        nodePort: 30100