---
# Source: loki-stack/charts/promtail/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: v1-promtail
  namespace: loki
  labels:
    app: promtail
    chart: promtail-2.2.0
    heritage: Helm
    release: v1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: v1-promtail
subjects:
- kind: ServiceAccount
  name: v1-promtail
