---
# Source: loki-stack/charts/promtail/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: v1-promtail
  namespace: loki
  labels:
    app: promtail
    chart: promtail-2.2.0
    heritage: Helm
    release: v1
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [v1-promtail]
