apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: consul-server
  namespace: consul
  labels:
    app: consul
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: consul
      component: server
