api:
  insecure: true
  dashboard: true
  debug: true

ping: true

accessLog: {}

log:
  level: info

metrics:
  prometheus: {}

entryPoints:
  traefik:
    address: ":9000"
  web:
    address: ":8000"
  websecure:
    address: ":8443"
  web-int:
    address: ":9080"
  websecure-int:
    address: ":9443"

providers:
  file:
    filename: /etc/traefik/dynamic.yaml
  kubernetescrd: {}
