---
# Source: loki-distributed/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: v1-loki-distributed
  labels:
    helm.sh/chart: loki-distributed-0.31.0
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: v1
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    auth_enabled: false
    
    server:
      http_listen_port: 3100
    
    distributor:
      ring:
        kvstore:
          store: memberlist
    
    memberlist:
      join_members:
        - v1-loki-distributed-memberlist
    
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0
    
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
    
    schema_config:
      configs:
      - from: 2020-05-15
        store: aws
        object_store: s3
        schema: v11
        index:
          prefix: loki
    
    storage_config:
      aws:
        s3: "s3://us-east-1/loki-techniumlabs"
        dynamodb:
         dynamodb_url: "dynamodb://us-east-1"
    
    chunk_store_config:
      max_look_back_period: 0s
    
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
    
    query_range:
      align_queries_with_step: true
      max_retries: 5
      split_queries_by_interval: 15m
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h
    
    frontend_worker:
      frontend_address: v1-loki-distributed-query-frontend:9095
    
    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
    
    compactor:
      shared_store: filesystem
    
    ruler:
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      alertmanager_url: https://alertmanager.xx
      external_url: https://alertmanager.xx
