apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - serviceaccount.yaml
    - service-memberlist.yaml
    - configmap.yaml
    - distributor/deployment-distributor.yaml
    - distributor/service-distributor.yaml
    - querier/statefulset-querier.yaml
    - querier/service-querier.yaml
    - querier/service-querier-headless.yaml
    - ingester/statefulset-ingester.yaml
    - ingester/service-ingester.yaml
    - ingester/service-ingester-headless.yaml
    - query-frontend/deployment-query-frontend.yaml
    - query-frontend/service-query-frontend.yaml
    - gateway/deployment-gateway.yaml
    - gateway/configmap-gateway.yaml
    - gateway/service-gateway.yaml
    