---
# Source: loki-stack/charts/loki/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: v1-loki
  namespace: loki
  labels:
    app: loki
    chart: loki-2.3.0
    heritage: Helm
    release: v1
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [v1-loki]
