---
# Source: loki-stack/charts/loki/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: v1-loki
  namespace: loki
  labels:
    app: loki
    chart: loki-2.3.0
    heritage: Helm
    release: v1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: v1-loki
subjects:
- kind: ServiceAccount
  name: v1-loki
