---
# Source: loki-distributed/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: v1-loki-distributed
  labels:
    helm.sh/chart: loki-distributed-0.31.0
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: v1
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
     eks.amazonaws.com/role-arn: arn:aws:iam::411978606132:role/Loki