---
# Source: loki-distributed/templates/service-memberlist.yaml
apiVersion: v1
kind: Service
metadata:
  name: v1-loki-distributed-memberlist
  labels:
    helm.sh/chart: loki-distributed-0.31.0
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: v1
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 7946
      targetPort: http-memberlist
      protocol: TCP
  selector:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: v1
    app.kubernetes.io/part-of: memberlist
