---
# Source: aws-load-balancer-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    helm.sh/chart: aws-load-balancer-controller-1.1.6
    app.kubernetes.io/name: aws-load-balancer-controller
   aws-load-balancer-controller
    app.kubernetes.io/version: "v2.1.3"
    app.kubernetes.io/managed-by: Helm
  annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::23423234:role/AmazonEKSLoadBalancerControllerRole

