---
# Source: aws-node-termination-handler/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: v1-aws-node-termination-handler
  namespace: aws-node-termination-handler
  labels:
    app.kubernetes.io/name: aws-node-termination-handler
    helm.sh/chart: aws-node-termination-handler-0.15.1
    app.kubernetes.io/instance: v1
    k8s-app: aws-node-termination-handler
    app.kubernetes.io/version: "1.13.1"
    app.kubernetes.io/managed-by: Helm
